# Generated by Django 4.0.4 on 2022-05-02 16:39

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Record',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('country', models.CharField(max_length=100)),
                ('total_infections', models.IntegerField()),
                ('total_deaths', models.IntegerField()),
                ('incidence', models.DecimalField(decimal_places=1, max_digits=7)),
                ('date', models.DateField(auto_now_add=True)),
            ],
        ),
    ]
